version: '3.8'

services:
  backend:
    build: ./ml-backend
    container_name: ml-backend
    ports:
      - '5000:5000'
    volumes:
      - ./ml-backend:/app
    working_dir: /app
    command: node index.js
    depends_on:
      - frontend

  frontend:
    build: .
    container_name: ml-frontend
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
